version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - ${APP_EXPOSED_PORT}:8000
    volumes:
      - app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver ${APP_HOST}:${APP_EXPOSED_PORT}"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_EXPOSED_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - APP_PROTOCOL=${APP_PROTOCOL}
      - APP_HOST=${APP_HOST}
      - APP_EXPOSED_PORT=${APP_EXPOSED_PORT}
      - REDIS_EXPOSED_PORT=${REDIS_EXPOSED_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXPOSED_PORT}:5432
    restart: on-failure

  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - ${REDIS_EXPOSED_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    environment:
      - REDIS_EXPOSED_PORT=${REDIS_EXPOSED_PORT}

  celery:
    build:
      context: .
    restart: on-failure
    command: celery -A emailer worker -l debug -B
    volumes:
      - celery:/app
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_EXPOSED_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    depends_on:
      - db
      - redis
      - app

volumes:
  redis:
    driver: local
  app:
    driver: local
  celery:
    driver: local

