# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-29 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_running',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='opened_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
