# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230201_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='error_on_send',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
